### ISSUE TITLE
Why `macOS Menu App`? 

### ISSUE THREAD

**Issue by nelsonic** [dwyl/macos-menu-bar-app-tutorial#1]
# ⚠️ Disclaimer: Yes, this is `macOS` Specific 🍏 

This tutorial is _ultra-specific_ to people with a `mac` computer. There's no getting around it. `#SorryNotSorry`
I expect to continue using a `mac` as my "daily driver" computer for the foreseeable future. 🙃 
See: [dwyl/learn-flutter#mac-focussed](https://github.com/dwyl/learn-flutter#mac-focussed-) 📱 ==💰 

We would be _delighted_ if someone using `Linux` e.g. `Ubuntu`  made a _similar_ tutorial. 🐧 🙏 

# Context: The Problem ⏳ 

At present I'm using the [`MVP`](https://github.com/dwyl/mvp/) web version of the @dwyl app: https://mvp.fly.dev

<img width="808" alt="image" src="https://github.com/dwyl/macos-menu-bar-app-tutorial/assets/194400/4ec984fa-c219-41ae-b7c4-ffc29d607aa0">

It works fine. Buuuuttt ... I find myself having to <kbd>command</kbd>+<kbd>Tab</kbd> to view the `Timer` ... ⏳ 
This wastes time and focus in the context-switch. 

What I _want_ is the ability to see the `Timer` and `item` _keyword_ in the `macOS` Menu Bar. 

e.g: 
```
PR #42 | 01:37:02
```

Just enough info for me to know what I'm focussing on and how much time has passed.

More detail:
https://support.apple.com/en-gb/guide/mac-help/mchlp1446/mac
<img width="1251" alt="image" src="https://github.com/dwyl/macos-menu-bar-app-tutorial/assets/194400/e653531e-bf20-402c-821a-1a0fda93a50d">

# Starting Point 🤞 

Creating Menu Bar App in macOS Using AppKit: https://youtu.be/uszImMe0CsU looks like a good starting point. 🤞 
<img width="803" alt="image" src="https://github.com/dwyl/macos-menu-bar-app-tutorial/assets/194400/ee92795c-5f43-4698-b60b-6d162e7a2c10">
https://gist.github.com/azamsharp/a48f1ab9e3db6a569065d9cc52ffe8d8

# Todo ✅ 

+ [ ] Follow the Azam tutorial and try to build the basic Menu Bar App.
+ [ ] Document _all_ the steps along the way.
+ [ ] Include screenshots of the finished App.

# _`.then`_ What? 🤷‍♂️ 

If we get this working _natively_ on `macOS` we can explore including it in our `Flutter` app 
or vice versa include the `Flutter` App in an `iOS/macOS/iPadOS` project. 💭 

This is _definitely_ a "power user" feature. Only relevant to `people` with a `Mac`. 
But since that corresponds with people who `pay` for `Apps`, it makes sense to build it.
Even if it's only used by a couple hundred people, the quality-of-life enhancement is worth it.

**Comment by nelsonic** [comment]
Looks like we _might_ be able to build this directly in `Flutter` with an `AppKit` component: 

https://www.en.techgaku.com/create-mac-app-menubar-with-flutter/
![image](https://github.com/dwyl/macos-menu-bar-app-tutorial/assets/194400/4deb65a8-cd47-4363-8135-63a3db7fda79)

https://github.com/mynameiskenlee/flutter_macos_menubar_example
![image](https://github.com/dwyl/macos-menu-bar-app-tutorial/assets/194400/336aabd2-6e17-4a29-9d8a-aaa06df02509)

But the above video is still relevant. 👌

**Comment by joaomagfreitas** [comment]
> We would be delighted if someone using Linux e.g. Ubuntu made a similar tutorial. penguin pray

Doing this on Linux is not so feasible as Mac, since there are a ton desktop environments for various distributions, but I would be very glad to research what can be done (can test on Ubuntu and ElementaryOS).

**Comment by nelsonic** [comment]
https://github.com/Jaennaet/pISSStream
![image](https://github.com/user-attachments/assets/3bb96a28-b7e7-42cd-8c14-730b82a718f4)


Currently top of HN: https://news.ycombinator.com/item?id=42505454
![image](https://github.com/user-attachments/assets/de1df1b0-d251-42ad-bd15-39a6ca193946)

_obviously_ don't focus on the fact that it's an app to track a very toilet humour subject. 🙄 
but it's a great tech/skill showcase for @Jaennaet 🥷

**Comment by Jaennaet** [comment]
I HAVE BEEN SUMMONED.

Whuh, what?

> but it's a great tech/skill showcase for @Jaennaet 🥷

Dear gods I hope not.

**Comment by nelsonic** [comment]
@Jaennaet as your only public repo https://github.com/Jaennaet?tab=repositories
Not much else to go on to assess skill ... 😜 

![image](https://github.com/user-attachments/assets/931a47a1-8836-40a1-9a10-f464200228cb)


![image](https://github.com/user-attachments/assets/cee54821-86e4-4a69-bb1a-8baf8fb47ac6)

Either you've created this account as a throw-away / anonymous for this single project 
e.g. to not directly associate your main account with urine tracking. 😉 

https://github.com/Jaennaet/pISSStream/graphs/contributors
![image](https://github.com/user-attachments/assets/3906abb3-3929-425b-8f84-d2270487ecbd)


https://github.com/durul
![image](https://github.com/user-attachments/assets/210843bd-9b25-4bcc-8912-930c792eba47)

Either way it's a fun read: https://github.com/Jaennaet/pISSStream/pull/3
And a great way to learn the tech with a light-hearted project.

Bravo! 👏
